name: bible
description: The Holy Bible in languages
version: 1.0.0+20

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # Custom
  path_provider: ^1.1.0
  http: ^0.12.0

  flutter_reorderable_list: ^0.1.3
  flutter_slidable: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/book.json

  fonts:
    - family: Padauk
      fonts:
        - asset: assets/fonts/Padauk-Regular.ttf
        - asset: assets/fonts/Padauk-Bold.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
