name: bible
description: the Holy Bible in languages
version: 1.0.1+35

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  usage: ^3.4.1
  cupertino_icons: ^0.1.2
  # Custom
  path_provider: ^1.2.0
  http: ^0.12.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.1

  flutter_reorderable_list: ^0.1.3
  pull_to_refresh: ^1.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/book.json

  fonts:
    - family: Padauk
      fonts:
        - asset: assets/fonts/Padauk-Regular.ttf
