name: bible
description: the Holy Bible in languages

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version: 1.0.4-beta.1+44
version: 1.0.4+44

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # LLocal lidea package, only in development
  lidea:
    path: ../lidea
  # Github lidea package
  # lidea:
  #   git:
  #     url: git://github.com/laisiangtho/lidea.git
  #     ref: main

  # Custom
  # hive_flutter: ^1.0.0
  # package_info: ^2.0.0
  # path_provider: ^2.0.1
  # http: ^0.13.1
  # firebase_core: ^1.0.2
  # firebase_analytics: ^7.0.1
  share: ^2.0.1
  # flutter_reorderable_list: ^0.1.4
  flutter_reorderable_list: ^1.0.0
  # flutter_tts: ^1.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/book.json

  fonts:
    # - family: Mm3Web
    #   fonts:
    #     - asset: assets/fonts/Mm3Web_V3.000.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
    - family: LaiSiangtho
      fonts:
        - asset: assets/fonts/LaiSiangtho.ttf
    - family: Mm3Web
      fonts:
        - asset: assets/fonts/Mm3Web.ttf