name: bible
description: the Holy Bible in languages

# Remove this line to publish to pub.dev
publish_to: 'none'

# Previous version: 1.0.4-beta.1+44
version: 1.0.4+44

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Local lidea package, development only
  lidea:
    # path: ../lidea
    # Github lidea package
    git:
      url: git://github.com/laisiangtho/lidea.git
      ref: main

  # Custom
  hive_flutter: ^1.1.0
  share: ^2.0.4
  # flutter_tts: ^1.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/env.json
    - assets/bible.json

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        # - asset: assets/fonts/Lato-Thin.ttf
        # - asset: assets/fonts/Lato-Light.ttf
        # - asset: assets/fonts/Lato-Italic.ttf
        # - asset: assets/fonts/Lato-Bold.ttf
    - family: LaiSiangtho
      fonts:
        - asset: assets/fonts/LaiSiangtho.ttf
    # - family: Mm3Web
    #   fonts:
    #     - asset: assets/fonts/Mm3Web.ttf